// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkjvWvmJ_PKKvuAK4iR2f60c5cIqCn63E',
    appId: '1:473619774469:web:482584f6ef1fa1ce6cf06c',
    messagingSenderId: '473619774469',
    projectId: 'kasir-batik',
    authDomain: 'kasir-batik.firebaseapp.com',
    storageBucket: 'kasir-batik.firebasestorage.app',
    measurementId: 'G-QWCFKNWB1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhGvxqD2CpI5_n6ghgHzR6UHOZEamyp34',
    appId: '1:473619774469:android:ca81cf4cfcb943d76cf06c',
    messagingSenderId: '473619774469',
    projectId: 'kasir-batik',
    storageBucket: 'kasir-batik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc6MqHQPQ1jklLSdfArhvf-Tt13M1r8M4',
    appId: '1:473619774469:ios:b8a987384e36ee6e6cf06c',
    messagingSenderId: '473619774469',
    projectId: 'kasir-batik',
    storageBucket: 'kasir-batik.firebasestorage.app',
    iosClientId: '473619774469-1i2j4k8g7gi1qb4giggnl8s7br0cihsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasirBatik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc6MqHQPQ1jklLSdfArhvf-Tt13M1r8M4',
    appId: '1:473619774469:ios:b8a987384e36ee6e6cf06c',
    messagingSenderId: '473619774469',
    projectId: 'kasir-batik',
    storageBucket: 'kasir-batik.firebasestorage.app',
    iosClientId: '473619774469-1i2j4k8g7gi1qb4giggnl8s7br0cihsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasirBatik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkjvWvmJ_PKKvuAK4iR2f60c5cIqCn63E',
    appId: '1:473619774469:web:c43bdf19ed2124596cf06c',
    messagingSenderId: '473619774469',
    projectId: 'kasir-batik',
    authDomain: 'kasir-batik.firebaseapp.com',
    storageBucket: 'kasir-batik.firebasestorage.app',
    measurementId: 'G-2T6JKF82YJ',
  );
}
